### ISSUE TITLE
[Feature Request] (Important) Show app names and icons and search for uninstalled apps

### ISSUE THREAD

**Issue by at-pyrix** [samolego/Canta#103]
Please display the app name and icon too instead of just package name. Also, a search feature for uninstalled apps would be really helpful too.

Thanks

**Comment by samolego** [comment]
Duplicate of #70, so closing this

**Comment by samolego** [comment]
> instead of just package name

You're probably using the FDroid version, which is outdated. The new GH versions already show the app name.

**Comment by at-pyrix** [comment]
Thanks!
