### ISSUE TITLE
Canta can't see Google Calendar

### ISSUE THREAD

**Issue by rafnov** [samolego/Canta#105]
It's the second device I am trying to do this - remove Google Calendar, but Canta seems being blind for it, while another app can see. I have any filters disabled, just looking by the english word "calendar" or polish "kalendarz" - no result.
Why and how to fix?
Devices are Realme 7 Pro (RMX2170) and Realme GT Neo 2 (RMX3370).

![Screenshot_2024-10-23-08-41-05-77_3c338d3aae3d76ada10886473fa3a1be.jpg](https://github.com/user-attachments/assets/dad68d67-7da0-4592-821e-34425f8a7401)

![Screenshot_2024-10-23-08-40-39-08_718a221d6c53e9d44e23988b91117061.jpg](https://github.com/user-attachments/assets/448e3c43-2bd9-4351-9528-4824eb225b23)

![Screenshot_2024-10-23-08-50-29-70_718a221d6c53e9d44e23988b91117061.jpg](https://github.com/user-attachments/assets/5be3466d-0485-407d-a79e-8465c3a47598)

**Comment by rafnov** [comment]
Sorry for twin screenshots, I can't edit via app so here is the 2nd
![Screenshot_2024-10-23-08-40-39-08_718a221d6c53e9d44e23988b91117061.jpg](https://github.com/user-attachments/assets/f886636f-cc7b-43ee-afb9-4f5a0e7cc5ce)

**Comment by samolego** [comment]
Humm, might be a language issue ...

**Comment by rafnov** [comment]
> Humm, might be a language issue ...

I don't know, but... Seems fixed in 2.2.1.
Thank you.
![Screenshot_2024-10-25-21-11-05-86_3c338d3aae3d76ada10886473fa3a1be.jpg](https://github.com/user-attachments/assets/7b7aa218-9920-4840-887b-7a7b9e40711f)
