### ISSUE TITLE
[Feature Request] Select all button and search for uninstalled apps.

### ISSUE THREAD

**Issue by fabcard** [samolego/Canta#106]
Hello, I'm a new Canta user. Sorry if I'm posting on a wrong place, and please excuse my poor English, it's not my main.
Could you please add a “select all” button to select all apps when I choose Recommended, Advanced, etc, just like the “deselect all” button already present on the program? It's just a bit annoying to select apps one by one on the list, just a QoL feature.
Also, if you can add a search button to search the uninstalled apps list, it would be much appreciated. The search right now just looks on installed apps list.
Thanks in advance.

**Comment by samolego** [comment]
Please update to Github release version, as it has the latest version with deleted search as well.

Select all will not be added since it's too "dangerous". Not all recommended apps should be uninstalled.

**Comment by anaxonda** [comment]
I hope you could reconsider the request of having a "select all" button. It can be hidden behind a warning or need to be enabled in settings. I think most users can handle the responsibility?

It would be much so easier to deselect a few apps than selecting one by one.

**Comment by starbrights** [comment]
+1: 
you apply a filter (most likely "recommended") and won't click 200 buttons. 
For sure in "advanced" or "expert" you have to be more carefully and will do it step by step.

Also fine would be to export/import a setting - so that you can repeat it or share it.

**Comment by samolego** [comment]
Humm, perhaps pnly when recommended is selected, but I'm still on the "no" side atm. Sorry :/. Perhaps a discussion should be made to change my mind :)?


Canta is (should) be pretty simple to use, which puts more power to the end user (that's great, but there's more risk as well).


Import/export will probably come when I have time & will. They should be compatible with UAD imho, so first I'll need to check their setup.
