### ISSUE TITLE
Option to disable instead of uninstall

### ISSUE THREAD

**Issue by ramxdier** [samolego/Canta#11]
Useful feature to avoid bootloop on Xiaomi devices.

**Comment by samolego** [comment]
Which app uninstall has lead you to bootloop? Was there anything in description?

**Comment by ramxdier** [comment]
I don't know exactly which application caused the bootloop but it is the first time it has happened.
I have been using UAD for years, only uninstalling applications marked as _recommended_ and _advanced_.
How could I track down the problematic app?

**Comment by samolego** [comment]
It'd be hard ... I guess you could try to binary search it, though it's going to be a pain ....
