### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Robert987** [samolego/Canta#112]
Canta will not allow removal of apps.  It says "uninstall canceled".  I have tried repeatedly, with the same result, and a different number of apps.  
I expected it to do as advertised. Versions are Android 14, Canta 1.4.1, and Shizuku 13.5.4r1050.adeaf2d.
I'm sorry I don't know Logcat.

**Comment by samolego** [comment]
Please update to canta >= 2.0.0
