### ISSUE TITLE
Version 1.2.0 flagged on virustotal

### ISSUE THREAD

**Issue by Frays8437** [samolego/Canta#12]
https://www.virustotal.com/gui/file/988309b085f8f496a5f1fcda739c75474cd3b83fdc6f1cf83d62ae7706b27587/detection

**Comment by samolego** [comment]
Hum, I have no idea why. Will have to inspect the test.

App is safe though 🙃, you can check the source.

**Comment by samolego** [comment]
> lib/arm64-v8a/libflutter.so

Seems like flutter is causing that

**Comment by Frays8437** [comment]
> Hum, I have no idea why. Will have to inspect the test.
> 
> App is safe though 🙃, you can check the source.

If I known how to read a code I wouldn't have to check it on virustotal :D
