### ISSUE TITLE
Private Spaces Dependency

### ISSUE THREAD

**Issue by Faulhait** [samolego/Canta#127]
# Required packages for private space feature

### Private Spaces

Private spaces are a new feature on Android 15 that allow the users to have something similar to a second Profile except less prone to issues and better accessibility.

### Issue

Private spaces were not in my system settings. After fixing the issue (see *Context* and confirming the functionality I removed the packages below again and the private spaces feature continued to be in my app menu but would not launch.

### Context

The feature was not available on my pixel device after updating to the latest Android version. I pinned down the missing package by process of elimination after reinstalling all packages deleted with Canta. I deleted the packages (see *Dependencies*) due to being tagged as *recommended* and kept them deleted since there weren't any issues.

---

### Dependencies

# 1
**name**
com.google.pixel.camera.services.PersistentApplication

**package**
com.google.pixel.camera.services

**description**
CameraIDRemapper and a lot of Debug stuff

# 2
**name**
Webcam Services

**package**
com.android.DeviceAsWebcam

**description**
Using smartphone as webcam

---

### Suggestion

Changing the tag for the two mentioned packages from ***Recommended*** to ***Advanced*** as well as updating the description to warn the user of the end result.

**PS**
I suspect the first package to be specific to pixel phones. It would be good to find the corresponding packages for other devices and apply the same changes there as well (assuming the issue exists on those devices too).

**PPS**
How come the name is longer than the package name for the first dependency?

---

Dear developer, thank you for creating Canta. The app is great.

**Comment by samolego** [comment]
Hi there! I'd kindly ask you to report the issue of moving the app to Advanced section in the UAD github (visit https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/)
Canta gets the info for apps from there :).

Regarding PPS: Probably it's the main activity name as the fallback. I should probably make it use the last part only.
