### ISSUE TITLE
Google calculator doesn't show up

### ISSUE THREAD

**Issue by ojppe** [samolego/Canta#13]
[Google calculator](https://play.google.com/store/apps/details?id=com.google.android.calculator) (system app on my device) is not visible in the list.
Possibly not uninstallable?

**Comment by samolego** [comment]
That's weird.
Please follow the issue template; specify the versions & provide logcat

**Comment by ojppe** [comment]
Nothing Phone 1
Android 13
Canta 1.1.1
Shizuku 13.5.2

I
samo_lego.canta: Using Collector TypeCC GC.

E
samo_lego.canta: Not starting debugger since process cannot load the jdwp agent.
nativeloader: Configuring clns-4 for other
apk /data/app/~~3ZQdfqRF15Aedrzd0i3_oA==/
org.samo_lego.canta-es5k2Nhyv-D0B4k2fBUehQ==/
base.apk. target_sdk_version=33,
uses_libraries=, library_path=/data/

D
app/~~3ZQdfqRF15Aedrzd013_oA==/ org.samo_lego.canta-es5k2Nhyv-D0B4k2 fBUehQ==/ lib/arm: /data/app/~~3ZQdfqRF15Aedrzd0i3_oA==/ org.samo_lego.canta-es5k2Nhyv-D0B4k2fBUehQ==/ base.apk!/lib/armeabi-v7a, permitted_path=/ data:/mnt/expand: /data/user/0/ org.samo_lego.canta

V
Graphics Environment: ANGLE Developer option for 'org.samo_lego.canta' set to: 'default'

V
GraphicsEnvironment: ANGLE GameManagerService...
samo_lego.canta: type=1400 audit(0.0:664): avc: denied { read } for name="max_map_count" dev="proc" ino=434529 scontext=u:r:u 

W
ntrusted_app: s0:c186, c256, c512,c768 tcontext=u: object_r: proc_max_map_count:s0
tclass=file permissive=0 app=org.samo_lego.canta
samo_lego.canta: Cleared Reference was only
reachable from finalizer (only reported once)

W
samo_lego.canta: NativeAlloc concurrent copying GC freed 267253(13MB) AllocSpace objects, 211(10MB) LOS objects, 75% free, 8168KB/31 MB, paused 57us, 16us total 160.648ms

E samo_lego.canta: Invalid ID 0x00000000.

**Comment by samolego** [comment]
Please update Canta first.

Do other system apps show fine?

**Comment by ojppe** [comment]
Neo Store thinks 1.1.1 is the latest version.
Now on 1.2 but still no calculator. All other system apps are there.
