### ISSUE TITLE
[BUG] Canta won't uninstall Game Optimizing Service.

### ISSUE THREAD

**Issue by fabcard** [samolego/Canta#130]
**Describe the bug**
Canta doesn't uninstall Game Optimizing Service (com.samsung.android.game.gos) 

**To Reproduce**
1. Open Canta.
2. Select GOS on the list.
3. Click on delete.
4. GOS is removed from the list.
5. Close Canta.
6. Restart Canta after boot or not.
7. GOS is back on the list.
Note: Yes, Shizuku is running.

**Expected behavior**
GOS gets removed and doesn't come back after Canta restart.

**Version info**
 - Android version: 14
 - Canta version: 2.2.2
 - Shizuku version: 13.5.4.r104

**Comment by samolego** [comment]
Can you try uninstalling it via ADB directly? E.g. with UAD

**Comment by fabcard** [comment]
> Can you try uninstalling it via ADB directly? E.g. with UAD

Hello there. Using UAD the same thing happens.
I select GOS, click uninstall, it disappears from the list, I refresh the list and GOS is back.
Any idea how to fully remove GOS?
Thanks in advance.

**Comment by samolego** [comment]
You won't be able to do it then :(
