### ISSUE TITLE
[Feature] Root Mode

### ISSUE THREAD

**Issue by RudiBoy95** [samolego/Canta#134]
Hey there thanks for this app

Hopefully you can make it work with rooted phones as well 

This is the only app that requires shizuku on my phone...

**Comment by samolego** [comment]
SUI is supported for rooted devices (you need to install the module). Direct root support is not planned.

**Comment by RudiBoy95** [comment]
> SUI is supported for rooted devices (you need to install the module). Direct root support is not planned.

Forgot to say that SUI it's broken and again it would be an extra module for only 1 app 
I'm not developer but I thing making this work with both root and shizuku shouldn't be hard 

Cheers

**Comment by samolego** [comment]
Yeah I'm sorry but that's out of scope at least atm.
