### ISSUE TITLE
No app is showing.

### ISSUE THREAD

**Issue by MdSakifHossain** [samolego/Canta#16]
Problem:
app is just showing "Loading apps...".
And it's just loading and loading.

I'm using a realme narzo 50 phone.
Os: android 11
Installed the Shizuku app.
Installed Canta app.
Configured both of them successfully.

I've triple checked everything.
Nothing wrong on my side....

I just don't want to delete every single app by using a CLI based app.
It's just painful.
Please fix this error.

**Comment by samolego** [comment]
Duplicate of #3
