### ISSUE TITLE
Improvements for Canta

### ISSUE THREAD

**Issue by realgooseman** [samolego/Canta#18]
Hi @samolego,

This app is exactly what I needed. Thanks for making it.
I would like to suggest some improvements for the app, let me know what you think :

### **Interface**

- Dark mode support (switch light/dark theme option)
- Browse the uninstalled apps the same way as the installed ones (Not only showing the package name but also app icon, labels and description. For better clarity.)
- Maybe Material UI implementation in the future ?

### **Other**

- Localization support (setting up service like Chrowdin and give the growing community ability to contribute with translating the app)

> ### **Unrelated**
> 
> I can't uninstall **Samsung's Game Optimizing Service** app on Canta, it always comes back right after uninstallation. Is it a known issue ? is there a workaround ?
> 
> I got a Samsung Galaxy S10 (SM-G973F) running Android 12 / OneUI 4.1

**Comment by realgooseman** [comment]
Hi, thanks for clarifying.

**Uninstalled apps** : I don't know if it's possible but maybe an app-list save system that saves package names with details and shows it even on the uninstalled apps window ? Because figuring out what app is uninstalled from their package name only can be confusing.

**Material UI** : I don't know the proper term but just modernizing the UI design. I had the app called : [AppManager](https://github.com/MuntashirAkon/AppManager) in mind which does similar stuff to Canta but is way too bloated.


**I guess you didn't notice the unrelated part of my issue above but :** 

I can't uninstall Samsung's Game Optimizing Service app on Canta, it always comes back right after uninstallation. Is it a known issue ? is there a workaround ?

I got a Samsung Galaxy S10 (SM-G973F) running Android 12 / OneUI 4.1

**Comment by samolego** [comment]
> I can't uninstall Samsung's Game Optimizing Service app on Canta, it always comes back right after uninstallation. Is it a known issue ? is there a workaround?

Please open a separate issue for this.

**Comment by MillionsToOne** [comment]
> I'm not sure wym by material ui; app is already themed with material design components?

They probably mean it should use Jetpack Composed with MD3
