### ISSUE TITLE
[BUG] Can't uninstall Game Optimizing Service (GOS)

### ISSUE THREAD

**Issue by realgooseman** [samolego/Canta#19]
**Describe the bug**
I can't uninstall Game Optimizing Service app on Canta, it always comes back right after uninstallation on my Samsung device. 
Is it a known issue ? is there a workaround ?

**To Reproduce**
1. Open Canta
2. Search for "Game Optimizing Service" app
3. Select it
4. Uninstall it

**Expected behavior**
It should be uninstalled from the system but it always reappears in Canta and the installed apps on my phone.

**Version info**
 - Smartphone: Samsung Galaxy S10 (SM-G973F)
 - Android version: 12 / OneUI 4.1
 - Canta version: 1.2.0
 - Shizuku version: 13.5.2.r1028.2bbf671

**Comment by samolego** [comment]
Does it reappear after reboot or is it not even uninstalled?

**Comment by realgooseman** [comment]
No, it is not even uninstalled. I can still see the GOS app in Canta and in the applications menu in my phone settings. Still shows up after reboot too.

**Comment by samolego** [comment]
Can you uninstall it with Universal Android Debloater?

**Comment by realgooseman** [comment]
The Type-C port on my phone is broken, so can't use UAD I think (does UAD work wirelessly ?). Hence why Canta is a great idea.

In the meantime, I used aShell with uninstall command on my phone = uninstalling GOS doesn't work on there either. So the problem is likely not linked to Canta, just a very persistent system app even if it's safe to uninstall.

**Comment by samolego** [comment]
You can use wireless debugging if you have android 11+. Though if you couldn't uninstall it via shell, it might be something "special" of an app 😕.

**Comment by realgooseman** [comment]
Yes I think so, which is very annoying because I never play games on my phone, GOS drains battery because always working in the background + it regularly phones home.

**Comment by samolego** [comment]
If adb uninstall doesn't work, then there's no hope for canta ...

**Comment by methicodx** [comment]
I was tried this.
Canta showing uninstall but refresh main page GOS still installed.
Me to cant
