### ISSUE TITLE
ENHANCEMENTS

### ISSUE THREAD

**Issue by ghost** [samolego/Canta#22]
### Good day Developer!

Your app is very promising, I have two features in mind to make it a must have for anyone.

**Support importing uad_exported_selection.txt to auto select apps**

**Support work profile**

Thank you for your time and consideration

**Comment by Lg42tv** [comment]
> Wdym by 'Support work profile'?

[Work profile](https://support.google.com/work/android/answer/6191949?hl=en) is a separate and self-contained profile that can be created with either [shelter](https://gitea.angry.im/PeterCxy/Shelter) or [insular](https://gitlab.com/secure-system/Insular)
