### ISSUE TITLE
[BUG] Motorola PAKS

### ISSUE THREAD

**Issue by RTB713** [samolego/Canta#24]
**Describe the bug**
A clear and concise description of what the bug is. Application called PAKS and PAK notifications on Motorola phones. I believe it has something to do with installing 3rd party apps. This app acts as an Admin. Sometimes I try to do things in my phone and am "blocked by IT" OR "Blocked by Admin" I use canta to uninstall, go back 3 mins later and it's right back. Please figure a way to keep this deleted. To be told I can't do something on my phone becaus I'm block by so and so is INFURIATING!!! Thank you. My first post like this so if I did it wrong my apologies!
![Screenshot_20240117-165157](https://github.com/samolego/Canta/assets/156967931/710cb671-acd2-4853-8e42-96d1c7487a42)

**To Reproduce**

**Expected behavior**

**Version info**
 - Android version: 
 - Canta version:
 - Shizuku version:

**Logcat**

<details>
  <summary>View logcat</summary>
  ```logcat
  paste logcat here
  ```
</details>

**Comment by samolego** [comment]
Is the app active as a "device admin"? Can you try disabling it, then uninstalling? Please provide Canta logcat as well.

Also, you can try to setup usb debugging with pc, then write
```shell
adb shell pm uninstall com.motorola.paks
```
and paste in here what it says.

**Comment by RTB713** [comment]
Sorry was out of town for a while. And no it wasn't active as admin when I tried to delete it. Also I got rid of that garbage phone, I couldn't take it anymore so I can't try the adb stuff and tell u what it says sorry

**Comment by samolego** [comment]
That's ok.

**Comment by chrushed** [comment]
you cant use adb on moto g stylus 2024

**Comment by puppykickr** [comment]
i have this same issue on a Motorola G Pure on android 12

it is only these two apps that wont respond to Canta.
