### ISSUE TITLE
[BUG] Realme reboots after 2 uninstalations

### ISSUE THREAD

**Issue by sosauce** [samolego/Canta#28]
Hello ! So I have I have a Realme phone (see specs below) and when I uninstall 1 app, only Canta will restart, but when I uninstall a 2nd app, my whole phone will reboot

Specs:

Realme C11 2021
32 bits processor (installed arm7 apk)
2GB RAM
Unisoc SC9863A (chipset)
Android 11 Realme UI Go

Hope you can fix that !

**Comment by samolego** [comment]
Can you uninstall it via adb?

**Comment by sosauce** [comment]
Yeah, with ADB I have no issues at all

**Comment by sosauce** [comment]
Where do I find this ?

**Comment by samolego** [comment]
Please see https://developer.android.com/tools/logcat
App package name is `org.samo_lego.canta`

**Comment by sosauce** [comment]
Okay, will do when I comeback home

**Comment by sosauce** [comment]
Sorry I never answered lmaooo, I bricked my realme so oh well..
