### ISSUE TITLE
YouTube Music is not in Canta

### ISSUE THREAD

**Issue by dragibusnoir** [samolego/Canta#30]
Describe the bug: 
I don't see YouTube Music in the list of applications to delete

Expected behavior
I recently installed Canta and was able to uninstall all the applications I wanted, but I couldn't find YouTube Music.

Version info
Smartphone: Google Pixel 6
Android version: 14 QPR 2
Canta version: 1.2.1
Shizuku version: 13.5.3

**Comment by samolego** [comment]
I'm sorry, did you check via search & scrolling? No filters active?

**Comment by dragibusnoir** [comment]
Yes I did all that, no filter active, I was able to delete YouTube but impossible to find YouTube Music

**Comment by samolego** [comment]
Does it show up now?

**Comment by dragibusnoir** [comment]
Yes, I had installed YouTube Music ReVanced, which hid YouTube Music. But YouTube Revanced doesn't hide YouTube.
