### ISSUE TITLE
[Sugestions] Garbage can hidden at search screen

### ISSUE THREAD

**Issue by rodrigo7373** [samolego/Canta#37]
1. When I touch the search bar and select some apps to freeze, I notice the red garbage can is hidden. 
2. It'd be even more helpful if there were a number counting the selected apps.

**Comment by samolego** [comment]
Those are both suggestions actually :).

When you click the uninstall button it says how many apps were selected

**Comment by rodrigo7373** [comment]
I have to close this issue now?

**Comment by samolego** [comment]
Depends, might be valuable to get other people's feedback on whether button should be hidden when searching.
