### ISSUE TITLE
Add app version after app name [FEATURE]

### ISSUE THREAD

**Issue by Character95** [samolego/Canta#40]
**Describe the bug**

**To Reproduce**
1. Go to 'Search'
2. Click on 'file name'
3. Scroll down to 'to duplicated file name'
5. See error 'don't know what app i uninstalled'

**Expected behavior**

**Version info**
 - Android version: 
 - Canta version:
 - Shizuku version:

**Logcat**

<details>
  <summary>View logcat</summary>
  ```logcat
  paste logcat here
  ```
</details>

**Comment by samolego** [comment]
That shouldn't be to hard to implement, if you're familiar with flutter, feel free to open a PR 😉

**Comment by samolego** [comment]
Implemented in 1.4.0. Thanks to @rbustillosdev

**Comment by Konace** [comment]
Hi Samolego, I'm a huge fan of your work and i just need help in setting this app up. Everything is tagged as "System" for some reason even Chrome. Is there anyway i can fix this?

![Screenshot_20240307_215038](https://github.com/samolego/Canta/assets/162591441/7b6f90d0-d49f-4ae8-a80e-ae3d990db700)

**Comment by Konace** [comment]
> Hi Samolego, I'm a huge fan of your work and i just need help in setting this app up. Everything is tagged as "System" for some reason even Chrome. Is there anyway i can fix this?
> 
> ![Screenshot_20240307_215038](https://private-user-images.githubusercontent.com/162591441/310902115-7b6f90d0-d49f-4ae8-a80e-ae3d990db700.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTk5NDMsIm5iZiI6MTcwOTgxOTY0MywicGF0aCI6Ii8xNjI1OTE0NDEvMzEwOTAyMTE1LTdiNmY5MGQwLWQ0OWYtNGFlOC1hODBlLWFlM2Q5OTBkYjcwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMzU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDk4MzYyYTFhNWQwN2Q4ZjI0Y2E0MjE5MjQzYzM4NWE4ZjkyZTZlMDA2M2MxMTA2MmE4OWU1NGI5OTk5ZDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCJP91kAI6DCn3VLOJsu9WvXJDWi6EtsOyBnOtiyRTI)

I've used this app before and it wasn't like this, idk what seems to be the problem now. Even when i factory reset my phone, everything will still be tagged as "System"

**Comment by samolego** [comment]
Hi, please open a new issue for this, do not write here.
btw, "system" is android's internal meaning, usually if app cannot be uninstalled by user / is preinstalled.
