### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by T-a-k-a-w-a** [samolego/Canta#42]
**No Description Provided**
In version 1.2 I downloaded canta and had fun with the recommendation feature in canta which makes it easy for me to delete things on my device realme
But when I updated 1.3 I lost this feature, even all the applications in Canta didn't display descriptions ? ^_^ 
So I now don't dare to delete anything because there is no guide about the app 

But I read an issue on Canta, that there was someone who experienced random reboots, actually me too but after many recommended applications I deleted,Looks like it's happening with the weather app
Maybe in the future a new description will be provided in the realme application 

**Version info**
 - Android version: 13 Realme UI 4
 - Canta version: 1.3.0 - 1.4.0 Still No description even the previous canta version 
 - Shizuku version: 13.5.3.r1036.fff3f87

 
![Screenshot_2024-03-04-14-24-03-35_3c338d3aae3d76ada10886473fa3a1be.jpg](https://github.com/samolego/Canta/assets/160514467/a781b2bf-a0af-4a58-bb91-d11c420d6422)

![Screenshot_2024-03-04-14-24-08-46_3c338d3aae3d76ada10886473fa3a1be.jpg](https://github.com/samolego/Canta/assets/160514467/541e8f88-ce4b-4024-b5ca-6c4d6b2c044a)

**Comment by samolego** [comment]
#39 first mentioned this, though I'll leave this one open.
UAD has changed formats, Canta needs to be updated (rn it fails to parse the suggestions)

https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/203

**Comment by T-a-k-a-w-a** [comment]
> #39 first mentioned this, though I'll leave this one open. UAD has changed formats, Canta needs to be updated (rn it fails to parse the suggestions)
> 
> [Universal-Debloater-Alliance/universal-android-debloater-next-generation#203](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/203)

OK, so in the future won't you be able to display descriptions for each application? thanks For the answer

**Comment by samolego** [comment]
No, it's possible, just parsing part needs to be updated.

**Comment by T-a-k-a-w-a** [comment]
> No, it's possible, just parsing part needs to be updated.

OK, thank you, I appreciate and look forward to the things you create, it's all very good!

**Comment by samolego** [comment]
Fixed in 1.4.1, sorry for the wait.

**Comment by HongYue1** [comment]
I'm still missing badges on A14 AOSP (matrixx OS)

**Comment by samolego** [comment]
Make sure ro use the 1.4.1 version.
