### ISSUE TITLE
[BUG] Removal type always shows "Any" after reopening

### ISSUE THREAD

**Issue by v1s7** [samolego/Canta#44]
**Describe the bug**
<details>
  <summary>GIF (420 KB)</summary>

![GIF_2024-03-16_00-43-43](https://github.com/samolego/Canta/assets/86906143/b639e8d8-2de9-4609-b75e-1357eb39502a)

</details>

**To Reproduce**
1. Open Canta
2. Go to «⋮»
3. Select any option other than Any in Removal type
4. Reopen «⋮»
5. Notice Removal type staying at Any, but the app list has sorted correctly

**Expected behavior**
It should stay at the selected option from Step 3

**Version info**
 - Android version: 13
 - Canta version: 1.4.1
 - Shizuku version: 13.5.4

**Logcat**

<details>
  <summary>View logcat</summary>

  ``` logcat
  later (is it even needed in this case?)
  ```

</details>

**Comment by samolego** [comment]
Thanks for report, should be easy fix. Logcat is not needed in this case :)

**Comment by samolego** [comment]
Fixed in bbe6718
