### ISSUE TITLE
[BUG] Shows "Reinstall complete", but nothing happens.

### ISSUE THREAD

**Issue by 851815** [samolego/Canta#45]
**Describe the bug**
I wanted to reinstall an app I accidentally uninstalled (com.samsung.android.incallui), but when I use the reinstall feature, it shows "reinstall complete" without reinstalling anything. Thinking it was a one-time thing, I decided to try and reinstall YouTube, but it didn't reinstall either.

**To Reproduce**
1. Uninstall any app
2. Try to reinstall it
3. ???
4. Void.

**Expected behavior**
I expected it to reinstall, simply put.

**Version info**
 - Android version: 9
 - Canta version: 1.4.0
 - Shizuku version: 13.5, adb

Cannot use logcat. If it's really needed I'll have to find a way to get it working

**Comment by samolego** [comment]
Should be fixed in 2.0.0
