### ISSUE TITLE
[BUG] Infinite loop (only wallpaper) ... urgent

### ISSUE THREAD

**Issue by KamiyaMinoru** [samolego/Canta#48]
I just using Canta and tried to remove some apps (includes some "system" but "recommended" ones - mainly theme related I think
And suddenly I get an "In an infinite loop without screens and wallpapers."

![image](https://github.com/samolego/Canta/assets/78710607/d5608133-37e8-47b5-98a5-983ab315bb89)
![image](https://github.com/samolego/Canta/assets/78710607/9e30760f-449b-4c30-9565-3444bdaeeb2b)
↑
loop between nothing and my wallpaper
p.s. I can still call my "SOS" via 9 times side button click, but in a wired status
![image](https://github.com/samolego/Canta/assets/78710607/dffa73d6-2f13-4600-b6d8-2a0bafecfa41)

But actually I guess my phone is in "brick" status, because I can not receive a call or message

I tried to connect my phone to my computer to get log etc but seems I can't,
Because I am stuck in the loop as described above (after I connect my phone to PC via cable - no popup window for selecting).

Phone: Realme X50
App version of Canta & Shizuku - latest, because I just downloaded them and started using
Launcher: Nova launcher

Could you give me some instructions to provide you necessary information to fix this problem?

**Comment by samolego** [comment]
1. Setup **adb** connection with the phone
2. Install the app back (`adb shell`, then `pm install <package name>` (sth. like this))

**Comment by KamiyaMinoru** [comment]
> 1. Setup **adb** connection with the phone
> 2. Install the app back (`adb shell`, then `pm install <package name>` (sth. like this))
> 3. Reboot

Hi, I
1. downloaded Android SDK Platform Tools ZIP, extract it, then try to do something
by following the instruction from below page:
https://www.xda-developers.com/install-adb-windows-macos-linux/

Anyway I can not operate my phone to swift to MTP nor allow USB debugging access
![image](https://github.com/samolego/Canta/assets/78710607/309a712a-69e7-4185-9a14-e77b5e31249e)

Could you teach me something more? Thank you very much

**Comment by KamiyaMinoru** [comment]
> If you don't find a way to authorize it, try if it's active in recovery mode.

Seems no...

normal mode →  unauthorized
safe mode →  unauthorized
recovery mode → no device detected
![image](https://github.com/samolego/Canta/assets/78710607/5871b0e2-d1c8-4276-8abc-1c62b555ae6a)

devmgmt.msc:
![image](https://github.com/samolego/Canta/assets/78710607/401a6e08-5c9d-4093-92e9-84d70e4d9bda)

control printers: 

no phone showed in recovery mode
![image](https://github.com/samolego/Canta/assets/78710607/6573f8d5-3b83-49a5-b00b-c6e1f9b45538)

but in normal mode
![image](https://github.com/samolego/Canta/assets/78710607/ab53b409-5be4-4127-88e4-b50faff8b23d)

**Comment by samolego** [comment]
Hum, have you tried posting on XDA developers? There might be some knowledgable people.

**Comment by KamiyaMinoru** [comment]
> Hum, have you tried posting on XDA developers? There might be some knowledgable people.

Hi, not yet (this is the first time I met this issue; and thought if I do not do Jailbreaking I will be safe)
I am trying to finding this forum, and do you have any suggestion I should post my question to (which sub-borad)?

Thank you

**Comment by samolego** [comment]
Try to find your phone's thread.
FYI, it's "rooting" not "jailbreaking" in Android world :).

Also, https://github.com/samolego/Canta?tab=readme-ov-file#features - you can not be safe if factory resetting is a deal breaker for you.

**Comment by KamiyaMinoru** [comment]
I will suggest you to review the "recommend" list, for I lost my phone & data due to believed your instruction (yes before deleting any app I even entered to confirm the description to see what are i.e. work with Pixel only).

**Comment by samolego** [comment]
Sorry to hear that, but it was clearly written you might need to do factory reset (clear phone data) if sth. goes wrong.
If you know which app caused it, please inform the universal android debloater.
