### ISSUE TITLE
Loading apps screen

### ISSUE THREAD

**Issue by Edgylatterdaysaint** [samolego/Canta#50]
I'm suffering from the "Loading apps" screen. I'm not super techy, so I don't know how to post in that thread. I have Galaxy Note 10+ Android 12. Shizuku is up to date, Canta has been up to date. 

I don't know how to save logs though. I'm sorry. I've tried downloading a Log Cat app or something and I really don't understand it.

**Comment by samolego** [comment]
Hi, sorry to hear that.

We already have the issue reported at #3 , so I'm closing this one.
