### ISSUE TITLE
Feature Request - Support for Android 8.0 and 8.1 Devices

### ISSUE THREAD

**Issue by OmarNazzal150** [samolego/Canta#56]
Dear samolego

I hope this message finds you well. I am writing to express my appreciation for your work on the Canta app, which I recently discovered on GitHub. It's an impressive tool that offers a great solution for managing apps without needing root access.

As an avid user of Android devices, I have a Samsung device running on Android Oreo (8.0/8.1), and I was excited about the possibility of using Canta. However, I noticed that the current version of Canta requires Android 9.0 or higher, which unfortunately leaves my device unsupported.

I understand that maintaining compatibility with older versions of Android can be challenging due to API changes and security considerations. Nevertheless, I believe that there is still a significant user base on Android Oreo who could greatly benefit from Canta's functionality.

Would it be possible to consider extending support to Android 8.0 and 8.1 devices? I am sure that many users, including myself, would be immensely grateful for such an update.

Thank you for considering this request and for your continued dedication to the Android community.

Best regards,

**Comment by samolego** [comment]
Sorry, it's not possible, solely due to technical reasons :( ...

**Comment by samolego** [comment]
HiddenApiBypass, library which is used by the app, requires sdk 28 (android 9)) ...

**Comment by OmarNazzal150** [comment]
Ok, fine. I will close this issue as not planned.
