### ISSUE TITLE
No, it does not require a factory reset to restore an "essential" (aka system) app

### ISSUE THREAD

**Issue by yochananmarqos** [samolego/Canta#6]
> if you remove essential app you will need to do factory reset, but that's it!

Nope. They can be removed and restored the same way via ADB:

https://www.xda-developers.com/uninstall-carrier-oem-bloatware-without-root-access/

**Comment by samolego** [comment]
I know about that. However if after rebooting you end up in bootloop, you will need a factory reset, that's what I meant.

Didn't really clarify that enough, will fix the description. Thanks for pointing out :).

**Comment by yochananmarqos** [comment]
Ah, thanks for clarifying. :+1:
