### ISSUE TITLE
[BUG] More of a feature request tbh.

### ISSUE THREAD

**Issue by crookyleeds** [samolego/Canta#60]
When choosing which apps to uninstall, you can see icons, tap the package, and be given information about what this package does.

When looking at which apps are already in the uninstalled state, this information is not available.

Is this something you would be able to implement?

It would be very useful.

**Comment by samolego** [comment]
Will come with app rewrite to jetpack compose :).

**Comment by crookyleeds** [comment]
> Will come with app rewrite to jetpack compose :).

Please may you explain what you mean?

**Comment by samolego** [comment]
No, I'm saying app is going under rewrite and this will be part of next version.

**Comment by crookyleeds** [comment]
Ooh brilliant.

**Comment by samolego** [comment]
Implemented in 2.0.0

**Comment by crookyleeds** [comment]
You're an absolute legend
Thank you so much.
