### ISSUE TITLE
[Feature Request] Add "Unlisted" Option to Filters in Canta app

### ISSUE THREAD

**Issue by accr01** [samolego/Canta#61]
Dear Canta Project Developers,

I hope this message finds you well. I am writing to you with a suggestion regarding the Canta project on GitHub. It would be incredibly beneficial if you could consider incorporating an "unlisted" option into the filters for applications. This addition would allow users to view apps that are not listed in the universal debloat list.

Including such an option would significantly enhance the usability and flexibility of the Canta project, as it would empower users to identify and manage apps that fall outside the standard debloat parameters. This feature could be particularly useful for users who have specific preferences or requirements for their app selections.

Thank you for your attention to this matter. Your continued dedication to improving the Canta project is greatly appreciated by the community. I eagerly anticipate the possibility of seeing this enhancement implemented in future updates.

**Comment by samolego** [comment]
Hi there, could you provide some examples of such apps? I don't see a reason why UAD wouldn't see them ...

**Comment by samolego** [comment]
Wait I might have misunderstood. So you want a filter to list apps that don't have descriptions / badges yet essentially?
Why'd you need it though 🤔?

**Comment by accr01** [comment]
> Hi there, could you provide some examples of such apps? I don't see a reason why UAD wouldn't see them ...

Sorry for not responding earlier, my phone screen was broken and I just recently got it fixed, hehe. I'll explain exactly what I mean.In your app, you use the universal debloat list, right? Well, I was referring to adding an option to filter out the packages that are not registered in that list (i.e., the ones that have no description or anything and do not appear in the list).This would help us try uninstalling apps to see if we lose any functionality or gain performance, and to investigate what these apps are and contribute to the app list.

**Comment by accr01** [comment]
> Wait I might have misunderstood. So you want a filter to list apps that don't have descriptions / badges yet essentially?
> Why'd you need it though 🤔?

Yes, I was more or less referring to that. Oh, and I'd like you to consider adding an option to import and export profiles. These profiles would include uninstalled, frozen, and installed apps.

This way, we could backup the apps that we have uninstalled, frozen, and installed. It would be useful to gradually save uninstalled applications that we know do not affect the functioning of the phone. If we uninstall something we shouldn't have, we could restore the latest profile backup to revert the apps' state to that of the backup – whether they are installed, uninstalled, or frozen.

**Comment by accr01** [comment]
Ah, I forgot to mention, it would also be great if you could include an option to view uninstalled, installed, and frozen apps. That would make the app perfect, haha. I know it's a lot of additions, but they're the ones that would make it the perfect app.
