### ISSUE TITLE
［Feature Requests］Adding System Badge Information

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#65]
The app has system-only labels, so I'd like the ability to display only those.

**Comment by samolego** [comment]
You already have that option, see 3 dots and check system only.

**Comment by tokumei123456** [comment]
I'm sorry if this expression is misleading.
I would like you to add a function that displays only system apps that have not yet been categorized.
I would like you to add something like the yellow part in the image.
![Uploading Screenshot_20240602-225435~2.png…]()

**Comment by tokumei123456** [comment]
I'm sorry if this expression is misleading.
I would like you to add a function that displays only system apps that have not yet been categorized.
I would like you to add something like the yellow part in the image.
![Screenshot_20240602-225435~2](https://github.com/samolego/Canta/assets/171477482/15e26d81-05ab-40cb-8d86-9f739ffa6bb1)

**Comment by samolego** [comment]
Ah, sorry. Didn't understand it :sweat_smile: . This is same as #61 , so I'll keep this closed.
