### ISSUE TITLE
[Feature Requests]Adding user app badge information

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#66]
There is no badge information for user apps, so I would like to be able to display only user apps.

**Comment by samolego** [comment]
There's not really a point in displaying user apps only? You can already uninstall those.

**Comment by tokumei123456** [comment]
After initializing the device, the pre-installed apps are user apps, so I would like a feature to be added that displays only user apps to make it easier to uninstall them.
As an example, see the yellow circle in the image.
![Screenshot_20240602-230944~2](https://github.com/samolego/Canta/assets/171477482/49c28875-8429-48c1-a20e-60de05996080)
