### ISSUE TITLE
[Feature request] Support for sui module

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#67]
I fully understand that this app is not intended for root users, but please support the sui module.

**Comment by samolego** [comment]
Doesn't it work already with sui? You only have to grant the permission manually.

**Comment by tokumei123456** [comment]
This screen does not appear, so I cannot grant permissions.
![Screenshot_20240602-224332](https://github.com/samolego/Canta/assets/171477482/b988fb6a-9399-44cb-ae87-10db8f025867)

**Comment by tokumei123456** [comment]
I can't uninstall or restore using canta with the sui module.
Is the problem with this something wrong with my procedure?

**Comment by samolego** [comment]
Hum, I thought you can manually grant sui access, as I did something to support it.
The dialog isn't requested yet, would love to get someone with SUI installed to help ...

**Comment by tokumei123456** [comment]
Is there anything I can do?
I can't program ...
I hope the problem can be solved.

**Comment by samolego** [comment]
No, only wait ...

**Comment by tokumei123456** [comment]
Are you going to support SHIZUKU and Super User authority?
Would you like to be able to do uninstalled with Super User authority?

**Comment by samolego** [comment]
I'd like to however I haven't worked with SUI yet. I'm all open for PRs though, for those who know how to implement that.

**Comment by tokumei123456** [comment]
I'm sorry it's hard to communicate.
Are you going to give Canta directly to Canta without using a SUI module so that you can uninstall it?
As an example, like Package Manager.

https://f-droid.org/ja/packages/com.smartpack.packageManager/

**Comment by tokumei123456** [comment]
If you uninstall canta using the sui module, canta will crash.

**Comment by samolego** [comment]
Currently not.

**Comment by tokumei123456** [comment]
I see....
Hopefully someday these features will be implemented.
Thank you for being so selfish.

Please keep up the good work on the application development!
I'll be rooting for you!

**Comment by tokumei123456** [comment]
canta was compatible with the sui module.
My procedure was wrong.

**Comment by samolego** [comment]
Did you have to manually enable it?

**Comment by tokumei123456** [comment]
yes.
You need to do it manually.

If it were possible to display a screen like the one in the image, I would like to see this implemented, as it would eliminate the need to do it manually.
![335870044-b988fb6a-9399-44cb-ae87-10db8f025867](https://github.com/samolego/Canta/assets/171477482/64f460d5-1694-498d-9419-bc39bc36b3dd)
