### ISSUE TITLE
[BUG？] There is one DISABLED label mixed in with the Unclassified labels.

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#69]
There is one DISABLED label in the Unclassified label. Is this a bug?
I have tried reinstalling the canta app and restarting the device.
![Screenshot_20240603-023332](https://github.com/samolego/Canta/assets/171477482/96fba2ea-cef9-4d7f-a8b0-fe4684e2fea8)

**Comment by samolego** [comment]
No, that's working as intended
