### ISSUE TITLE
[Feature Request] Maintain database of removed apps with removal date and reinstall button

### ISSUE THREAD

**Issue by djbclark** [samolego/Canta#71]
I'm often in the position of not uninstalling an app because it was really hard to find and I'm afraid if I uninstall it I won't be able to find it later. 

Would be awesome if Canta could maintain a database of uninstalled apps with ascending/descending sort by name, size, uninstall date, install date, last used date. With buttons to reinstall or look at app in its associated store app (eg play store, f-droid).

**Comment by samolego** [comment]
Fixed the title of #47 so I'm closing as a duplicate
