### ISSUE TITLE
［Feature Requests］Adding a button

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#73]
I'd like a button to be introduced that allows you to check a checklist so that you can uninstall all at once.

I want it to look like the image.
![1718795525779~2](https://github.com/samolego/Canta/assets/171477482/72440eaa-0ab8-4522-ab15-2f3ea6d0cbf2)

**Comment by tokumei123456** [comment]
This means that pressing the arrow button will check all the boxes at once.
This feature makes uninstallation much easier.
![1718796965235~2](https://github.com/samolego/Canta/assets/171477482/80d48698-a64e-40cf-a1e5-7e0b53a11be4)

**Comment by samolego** [comment]
That's a bit risky, uninstalling all apps like that, I probably won't add it.

**Comment by tokumei123456** [comment]
How about a popup saying it's dangerous when clicking uninstall in bulk?
It would prevent people from pressing the wrong button.

In my case, I have 98 apps that I don't need and uninstalling them one by one is a hassle.

The resolution was reduced because the file size of the video was too large.
https://github.com/samolego/Canta/assets/171477482/ab310b9c-a83f-4808-96b1-08cf1b6b33ba
