### ISSUE TITLE
[Feature Requests］Last app tile is overlayed by FAB

### ISSUE THREAD

**Issue by tokumei123456** [samolego/Canta#74]
If the app you want to uninstall is at the bottom, the checklist overlaps the button.
This is inconvenient.
I would like the uninstall button to be moved a little to the left.
![Screenshot_20240619-202018~2](https://github.com/samolego/Canta/assets/171477482/111dae4f-04ba-47fa-bfdf-ae853d17ec69)

**Comment by samolego** [comment]
Will probably just extend the list woth empty item.

**Comment by tokumei123456** [comment]
Will probably just extend the list woth empty item.
What does this mean?
Sorry for my poor understanding.

**Comment by tokumei123456** [comment]
We think the reason why the checklist overlaps with the uninstall button is due to the short package name.
![Screenshot_20240620-072117~2](https://github.com/samolego/Canta/assets/171477482/72e46f69-04a8-490a-a4e1-b6aa27f7f03a)

**Comment by samolego** [comment]
Sorry, mistyped, meant *with*. Basically, you'll be able to scroll lower even when you reach last app tile.

**Comment by tokumei123456** [comment]
Does it mean that it will improve?
Or does it mean that you can still do it already?

**Comment by samolego** [comment]
I'll fix it when I have time

**Comment by tokumei123456** [comment]
Thank you very much!
