### ISSUE TITLE
Management of Shizuku on app opening

### ISSUE THREAD

**Issue by tGstep** [samolego/Canta#8]
Hi, the opening of the app is not always easy, it opens only if i open the app and then run shizuku with the app being open. 
Is there a way this can be made more easy to do?
Great app btw.

**Comment by samolego** [comment]
Sorry, shizuku needs to be activated, that's the only way. Canta depends on its API.

**Comment by samolego** [comment]
Oh, sorry, misunderstood. That's weird tbf, hasn't happened to me.
Which android are you using? Does the app stay in "loading" screen or just not uninstall the apps?

**Comment by samolego** [comment]
Could you provide logcat please, filtered for canta?
