### ISSUE TITLE
Recommended apps breaks System Navigation.

### ISSUE THREAD

**Issue by akarn911** [samolego/Canta#80]
These five recommended apps breaks the system navigation when switching between 3-button and gestures. Remove them from recommended list.
( I am using Motorola phone)
1. com.google.android.overlay.gmsconfig.comms
2. com.google.android.overlay.gmsconfig.geotz
3.
com.google.android.overlay.gmsconfig.personalsafety
4. com.google.android.overlay.modules.modulemetadata.forframework
5. com.google.android.overlay.modules.permissioncontroller.forframework

**Comment by samolego** [comment]
Hi! Please report that to https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/ as Canta fetches its list :). Thanks!

**Comment by akarn911** [comment]
OK
