### ISSUE TITLE
[BUG] Canta is not visible in Android TV Home

### ISSUE THREAD

**Issue by kastentop2005** [samolego/Canta#86]
**Describe the bug**
There is no app banner on the home screen

**To Reproduce**
1. Install the application
2. Try to look for in on Android TV

**Expected behavior**
The app banner is displayed correctly

**Version info**
 - Android version: 11
 - Canta version: 2.2.0
 - Shizuku version: 13.5.4

**The fix**
Do this:
https://github.com/dovecoteescapee/ByeDPIAndroid/pull/86/commits/4ce4d3a41d0ef089e6f0914f0ab515f94b2a8022

**Comment by samolego** [comment]
Thanks for reporting!

**Comment by KittyBua** [comment]
Ich mache meine Banner schon lange mit dem 😁 

https://atvlauncher.trekgonewild.de/index.php

**Comment by samolego** [comment]
You can submit PR if you want 😉

**Comment by KittyBua** [comment]
What is PR ?

Samo Hribar ***@***.***> schrieb am Do., 28. Nov. 2024, 10:14:

**Comment by KittyBua** [comment]
With adb TV No Work deinstall

And With PC Work this

adb shell pm disable-user --user 0

With adb TV No Work

And what is PR

Mfg

Franz Eibel ***@***.***> schrieb am Do., 28. Nov. 2024, 10:41:

**Comment by samolego** [comment]
PR is pull request (if you wanted to add banner).

**Comment by KittyBua** [comment]
A OK Here is the Banner 

https://www.dropbox.com/scl/fi/5xsu9bxhpoxszgx05hbzq/Canta_ATV.apk?rlkey=wtr0odlpnalyuosd9smwuhiap&st=vttyzkz6&dl=1

And With Remote No Work the deleted only With USB Mouse the Papierkorb Rechts unten mfg 😂
