### ISSUE TITLE
It's not bug but I confused with these two documents

### ISSUE THREAD

**Issue by kasrarouhi** [samolego/Canta#88]
**Describe the bug**

I wanna know different between vendor.qti.imsrcs and org.codeaurora.ims because documents are little same . If I delete one of these to IMS works normally or will be worse. Which is better to delete one of these to Not break IMS functionality
![Screenshot_2024-08-24-20-23-22-191_org samo_lego canta](https://github.com/user-attachments/assets/bd5513fc-0b3d-4642-a074-1e08e279268b)

![Screenshot_2024-08-24-20-23-09-539_org samo_lego canta](https://github.com/user-attachments/assets/4637adc9-7227-4863-99fd-010819fba096)

**Comment by samolego** [comment]
I'm sorry, I don't know what these apps are for. Perhaps try asking in Universal Android Debloater?

**Comment by kasrarouhi** [comment]
Ok
