### ISSUE TITLE
ability for app to show only app with tag instead of hiding them

### ISSUE THREAD

**Issue by rezad1393** [samolego/Canta#9]
this app is used to remove app that bloating the device.
and tags show the level of app bloating and safe to removeness.

instead of user having to search the list for "recommended", it is better to add an option to show only a tag (like recommended).

this way user only sees those that are recommended to remove.

right now there is options to hide them (which have its uses for some) that is not really useful for this app usage.

**Comment by samolego** [comment]
Thanks, I've been thinking the same. The next release will have this option :)
