### ISSUE TITLE
[Removing gms configs causes many apps to crash.]

### ISSUE THREAD

**Issue by Samscryption** [samolego/Canta#99]
Removing **com.google.android.overlay.gmsconfig.common** causes multiple apps(ex. TikTok, DuckDuckgo,..) to occasionally crash with an error message that asks you to uninstall webview updates.
This app has a recommended badge.

**Version info**
 - Android version: 14
 - Canta version: 2.2.1
 - Shizuku version: 13.5.4

**Comment by samolego** [comment]
Hi! Thanks for spotting, please report this onward to https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/
